<?php
/**
 * Image Worker - Processes images CSV generated by create_product_media.php
 * Reads CSV and imports images using Shopware API
 */

error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

// Get job_id from command line or query string
$jobId = $_GET['job_id'] ?? $_SERVER['argv'][1] ?? null;

if (!$jobId) {
    error_log("ERROR: No job_id provided");
    exit(1);
}

require_once __DIR__ . '/db_config.php';

// Parse job_id from command line argument if needed
if (strpos($jobId, 'job_id=') === 0) {
    $jobId = substr($jobId, 7);
}

error_log("=== IMAGE WORKER START: job_id=$jobId ===");
error_log("PHP Binary: " . PHP_BINARY);
error_log("Script: " . __FILE__);

try {
    $pdo = Database::getConnection();
    
    // Get job details
    $stmt = $pdo->prepare("SELECT * FROM vendor_import_jobs WHERE job_id = ? LIMIT 1");
    $stmt->execute([$jobId]);
    $job = $stmt->fetch(PDO::FETCH_ASSOC);
    
    if (!$job) {
        error_log("ERROR: Job not found: $jobId");
        exit(1);
    }
    
    error_log("Job found: type=" . $job['import_type'] . ", file=" . $job['file_path']);
    
    if ($job['import_type'] !== 'images') {
        error_log("ERROR: Job is not an images import: " . $job['import_type']);
        exit(1);
    }
    
    // Update job status to processing
    $pdo->prepare("UPDATE vendor_import_jobs SET status = 'processing', started_at = NOW() WHERE job_id = ?")->execute([$jobId]);
    
    // Process the images CSV
    $csvPath = $job['file_path'];
    
    if (!file_exists($csvPath)) {
        error_log("ERROR: CSV file not found: $csvPath");
        $pdo->prepare("UPDATE vendor_import_jobs SET status = 'failed', error_rows = ?, completed_at = NOW() WHERE job_id = ?")->execute([$job['total_rows'], $jobId]);
        exit(1);
    }
    
    // Load Shopware
    require_once __DIR__ . '/../vendor/autoload.php';
    
    $classLoader = require __DIR__ . '/../vendor/autoload.php';
    $dotenv = new \Symfony\Component\Dotenv\Dotenv();
    $dotenv->loadEnv(__DIR__ . '/../.env.local');
    
    $appEnv = $_ENV['APP_ENV'] ?? 'dev';
    $debug = ($_ENV['APP_DEBUG'] ?? '1') !== '0';
    
    $kernel = \Shopware\Core\Framework\Adapter\Kernel\KernelFactory::create(
        environment: $appEnv,
        debug: $debug,
        classLoader: $classLoader
    );
    $kernel->boot();
    
    $container = $kernel->getContainer();
    $dbConnection = $container->get(\Doctrine\DBAL\Connection::class);
    $pdo = $dbConnection->getNativeConnection();
    
    // Process images from CSV
    $handle = fopen($csvPath, 'r');
    $header = fgetcsv($handle, 0, ';');
    
    if (!$header) {
        throw new Exception('Invalid CSV file - no header');
    }
    
    // Find column indices
    $productNumberIdx = array_search('productNumber', $header);
    $coverIdx = array_search('cover', $header);
    $mediaIdx = array_search('media', $header);
    
    if ($productNumberIdx === false || $coverIdx === false || $mediaIdx === false) {
        throw new Exception('CSV missing required columns: productNumber, cover, media');
    }
    
    $mediaRepo = $container->get('media.repository');
    $fileSaver = $container->get(\Shopware\Core\Content\Media\File\FileSaver::class);
    $context = \Shopware\Core\Framework\Context::createDefaultContext();
    
    // Get product media folder
    $folderId = $pdo->query("
        SELECT LOWER(HEX(mf.id)) 
        FROM media_folder mf
        JOIN media_default_folder mdf ON mf.default_folder_id = mdf.id
        WHERE mdf.entity = 'product'
        LIMIT 1
    ")->fetchColumn();
    
    if (!$folderId) {
        throw new Exception('Product media folder not found');
    }
    
    error_log("Media folder: $folderId");
    
    $processed = 0;
    $created = 0;
    $errors = 0;
    
    while (($row = fgetcsv($handle, 0, ';')) !== false) {
        $productNumber = trim($row[$productNumberIdx] ?? '');
        $coverUrl = trim($row[$coverIdx] ?? '');
        $mediaUrls = trim($row[$mediaIdx] ?? '');
        
        if (!$productNumber) {
            continue;
        }
        
        error_log("Processing: $productNumber");
        
        try {
            // Get product ID
            $stmt = $pdo->prepare("SELECT HEX(id) pid FROM product WHERE product_number = ?");
            $stmt->execute([$productNumber]);
            $product = $stmt->fetch(\PDO::FETCH_ASSOC);
            
            if (!$product) {
                error_log("  Product not found: $productNumber");
                $errors++;
                continue;
            }
            
            $productId = $product['pid'];
            
            // Clean up old media
            cleanupProductMedia($productId, $productNumber, $pdo);
            
            $mediaItems = [];
            $coverProductMediaId = null;
            
            // Process cover image
            if ($coverUrl) {
                $imagePath = resolveImagePath($coverUrl);
                
                if ($imagePath && file_exists($imagePath)) {
                    try {
                        $mediaId = \Shopware\Core\Framework\Uuid\Uuid::randomHex();
                        $mediaRepo->create([[
                            'id' => $mediaId,
                            'mediaFolderId' => $folderId,
                            'private' => false,
                            'name' => pathinfo($imagePath, \PATHINFO_FILENAME)
                        ]], $context);
                        
                        $file = new \Shopware\Core\Content\Media\File\MediaFile(
                            $imagePath,
                            mime_content_type($imagePath),
                            pathinfo($imagePath, \PATHINFO_EXTENSION),
                            filesize($imagePath)
                        );
                        
                        $destination = pathinfo($imagePath, \PATHINFO_FILENAME) . '-' . strtolower($productNumber) . '-cover';
                        $fileSaver->persistFileToMedia($file, $destination, $mediaId, $context);
                        
                        $productMediaId = \Shopware\Core\Framework\Uuid\Uuid::randomHex();
                        $mediaItems[] = [
                            'id' => $productMediaId,
                            'mediaId' => $mediaId,
                            'position' => 0
                        ];
                        $coverProductMediaId = $productMediaId;
                        $created++;
                        error_log("  ✓ Cover: $destination");
                    } catch (\Exception $e) {
                        error_log("  ERROR cover: " . $e->getMessage());
                        $errors++;
                    }
                } else {
                    error_log("  Cover not found: $coverUrl");
                    $errors++;
                }
            }
            
            // Process gallery images
            if ($mediaUrls) {
                $urls = explode('|', $mediaUrls);
                foreach ($urls as $pos => $url) {
                    $url = trim($url);
                    if (!$url) continue;
                    
                    $imagePath = resolveImagePath($url);
                    
                    if ($imagePath && file_exists($imagePath)) {
                        try {
                            $mediaId = \Shopware\Core\Framework\Uuid\Uuid::randomHex();
                            $mediaRepo->create([[
                                'id' => $mediaId,
                                'mediaFolderId' => $folderId,
                                'private' => false,
                                'name' => pathinfo($imagePath, \PATHINFO_FILENAME)
                            ]], $context);
                            
                            $file = new \Shopware\Core\Content\Media\File\MediaFile(
                                $imagePath,
                                mime_content_type($imagePath),
                                pathinfo($imagePath, \PATHINFO_EXTENSION),
                                filesize($imagePath)
                            );
                            
                            $destination = pathinfo($imagePath, \PATHINFO_FILENAME) . '-' . strtolower($productNumber) . '-g' . ($pos + 1);
                            $fileSaver->persistFileToMedia($file, $destination, $mediaId, $context);
                            
                            $mediaItems[] = [
                                'id' => \Shopware\Core\Framework\Uuid\Uuid::randomHex(),
                                'mediaId' => $mediaId,
                                'position' => $pos + 1
                            ];
                            $created++;
                            error_log("  ✓ Gallery $pos: $destination");
                        } catch (\Exception $e) {
                            error_log("  ERROR gallery: " . $e->getMessage());
                            $errors++;
                        }
                    } else {
                        error_log("  Gallery not found: $url");
                        $errors++;
                    }
                }
            }
            
            // Link media to product
            if (!empty($mediaItems)) {
                foreach ($mediaItems as $item) {
                    $stmt = $pdo->prepare(
                        "INSERT INTO product_media (id, version_id, position, product_id, product_version_id, media_id, created_at)
                         VALUES (UNHEX(?), UNHEX(?), ?, UNHEX(?), UNHEX(?), UNHEX(?), NOW(3))"
                    );
                    $stmt->execute([
                        $item['id'],
                        \Shopware\Core\Defaults::LIVE_VERSION,
                        (int)$item['position'],
                        $productId,
                        \Shopware\Core\Defaults::LIVE_VERSION,
                        $item['mediaId']
                    ]);
                }
                
                if ($coverProductMediaId) {
                    $stmt = $pdo->prepare("UPDATE product SET product_media_id = UNHEX(?) WHERE id = UNHEX(?)");
                    $stmt->execute([$coverProductMediaId, $productId]);
                }
                
                $processed++;
            }
        } catch (\Exception $e) {
            error_log("  Exception: " . $e->getMessage());
            $errors++;
        }
    }
    
    fclose($handle);
    
    // Update job status
    $pdo->prepare("UPDATE vendor_import_jobs SET processed_rows = ?, error_rows = ?, status = 'completed', completed_at = NOW() WHERE job_id = ?")
        ->execute([$processed, $errors, $jobId]);
    
    error_log("=== IMAGE WORKER COMPLETE ===");
    error_log("Processed: $processed, Created: $created, Errors: $errors");
    
} catch (\Exception $e) {
    error_log("IMAGE WORKER ERROR: " . $e->getMessage());
    error_log("Stack: " . $e->getTraceAsString());
    
    try {
        $pdo = Database::getConnection();
        $pdo->prepare("UPDATE vendor_import_jobs SET status = 'failed', completed_at = NOW() WHERE job_id = ?")->execute([$jobId]);
    } catch (\Exception $e) {
        // Silent fail
    }
    
    exit(1);
}

// Helper functions

function resolveImagePath($url) {
    // Handle URLs like http://shopware678.local/my-imports/Hakro/0105/m_model_p_0105_001_01.jpg
    // Or direct file paths
    
    if (strpos($url, 'http://') === 0 || strpos($url, 'https://') === 0) {
        $parsed = parse_url($url);
        if (isset($parsed['path'])) {
            $filePath = __DIR__ . $parsed['path'];
            if (file_exists($filePath)) {
                return $filePath;
            }
        }
    } else if (strpos($url, '/') === 0) {
        $filePath = __DIR__ . $url;
        if (file_exists($filePath)) {
            return $filePath;
        }
    }
    
    return null;
}

function cleanupProductMedia($productId, $productNumber, $pdo) {
    // Get all media for this product
    $sql = "SELECT HEX(m.id) as media_id, m.path FROM media m JOIN product_media pm ON pm.media_id = m.id WHERE pm.product_id = UNHEX(?)";
    $stmt = $pdo->prepare($sql);
    $stmt->execute([$productId]);
    $mediaFiles = $stmt->fetchAll(\PDO::FETCH_ASSOC);
    
    // Delete physical files
    foreach ($mediaFiles as $media) {
        $filePath = __DIR__ . '/' . $media['path'];
        if (file_exists($filePath)) {
            @unlink($filePath);
        }
    }
    
    // Reset product cover and delete media records
    $pdo->prepare("UPDATE product SET product_media_id = NULL WHERE id = UNHEX(?)")->execute([$productId]);
    $pdo->prepare("DELETE FROM product_media WHERE product_id = UNHEX(?)")->execute([$productId]);
    
    if (count($mediaFiles) > 0) {
        $mediaIds = array_map(function($m) { return $m['media_id']; }, $mediaFiles);
        $placeholders = implode(',', array_fill(0, count($mediaIds), 'UNHEX(?)'));
        $pdo->prepare("DELETE FROM media WHERE id IN ($placeholders)")->execute($mediaIds);
    }
}

exit(0);
